import React, { useEffect, useState } from "react";
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import axios from "axios";
import TwitterTask from "./components/TwitterTask";







export default function App() {


  const [username, setUsername] = useState("");
  const [result, setResult] = useState("");


  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log(username, "submit")
    try {
      const response = await axios.get(`http://127.0.0.1:3001/check/${username}`);
      setResult(response.data);
    } catch (error) {
      console.log(error);
    }
  };



  return (
    <div className="App">
      <header className="App-header">
        <h1>BIRBS</h1>
        <div className='Text-box'>
          <p>
            We happily welcome you to the Birbs, early followers!You have been invited to our park — where,
            as an early user , we will be giving a special airdrop to everyone who fulfills the following criteria:
          </p>
        </div>
        <div className='Text-box'>
          <i>
            <ul>
              <li> Are in the Birbs discord server.</li>
              <li>Post the verification tweet generated by this site on your twitter account.</li>
              <li>Are following our Twitter account </li>
            </ul>
          </i>
        </div>
        <div className='Activation-box'>

          {/* <div>
            <button className='Buttons'>Join Discord</button>
            <form onSubmit={handleSubmit}>
              <input type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
              />
              <button type="submit">Check</button>
              <p>{console.log(result)}</p>
            </form>
          </div> */}
          {
            result.success?(
            <div>
                <TwitterTask/>
            </div>):
            (
            <div>
              <button className='Buttons'>Join Discord</button>
              <form onSubmit={handleSubmit}>
                <input type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                />
                <button type="submit">Check</button>
                <p>{console.log(result)}</p>
              </form>
            </div>
            )
          }

        </div>
      </header>
    </div>
  )
}

