import React, {useState,useEffect} from "react";
import { useNavigate } from "react-router";
import './App.css'

const DiscordRedirect = ()=>{
    const [token, setToken] = useState("");
    const [tokenType, setTokenType] = useState("");
    const navigate = useNavigate();


    const DISCORD_CLIENT_ID = '1084465922548445236';
    const DISCORD_CLIENT_SECRET = 'C4Ick4quxOwMsN5OF6DU0xP2wTOt9ynG';
    const REDIRECT_URI = 'http://127.0.0.1:3000/discord-redirect';
  
    // const handleLogin = () => {
    //   const authorizationUrl ="https://discord.com/api/oauth2/authorize?client_id=1084465922548445236&redirect_uri=http%3A%2F%2F127.0.0.1%3A3000%2F&response_type=code&scope=identify";
    //   window.location.href = authorizationUrl;
    //   // client.login('MTA4NDQ2NTkyMjU0ODQ0NTIzNg.GTe5PC.3reapicH0WAUjYQr32K2wO5dYGhJumtl1UAO-Y');
  
    // };


    useEffect(() => {
        const fragment = new URLSearchParams(window.location.hash.slice(1));
        const accessToken = fragment.get('access_token');
        const tokenType = fragment.get('token_type');
        //     // const urlParams = new URLSearchParams(window.location.search);
    //     // const authorizationCode = urlParams.get('code');
        // Do something with the access token...
        // console.log(accessToken,'accessToken');
        // console.log(tokenType,"token-type")
        localStorage.setItem('accessToken',accessToken);
        // setToken(accessToken);
        // setTokenType(tokenType);
        localStorage.setItem('tokenType',tokenType);
        navigate('/',{state:{token:token}});
      }, [navigate]);
  
  
   
  
    // useEffect(() => {
  
  
  
    //     // const urlParams = new URLSearchParams(window.location.search);
    //     // const authorizationCode = urlParams.get('code');
  
    //     // if (authorizationCode) {
    //     //   // console.log(authorizationCode);
    //     //   // You have the authorization code, so you can proceed with Step 4
    //     //   axios.post('https://discord.com/api/oauth2/token',{
    //     //     'client_id':DISCORD_CLIENT_ID,
    //     //     'client_secret': DISCORD_CLIENT_SECRET,
    //     //     'grant_type': 'authorization_code',
    //     //     'code': authorizationCode,
    //     //     'redirect_uri':REDIRECT_URI,
    //     //     'scope':'identify'
    //     //   })
    //     //   .then((response)=>{
    //     //     console.log(response,"response")
    //     //   })
    //     //   .catch((error)=>{
    //     //     console.log(error,"err")
    //     //   })
   
    //     // } else {
    //     //   // The user has not authorized your app yet, so you can show a message asking them to authorize your app.
    //     //   console.log("aint got it")
    //     // }




  
    // },[])
    return(
        <div className="App">
            <header className="App-header">
                <h1>BIRBS</h1>
                <div className='Text-box'>
                    <p>
                        We happily welcome you to the grasslands, early caterpillars!You have been invited to our grasslands event — where,
                        as an early caterpillar to our development, we will be giving a special airdrop to everyone who fulfills the following criteria:
                    </p>
                </div>
                <div className='Text-box'>
                    <i>
                        <ul>
                            <li> Are in the Flutterfly discord server.</li>
                            <li>Post the verification tweet generated by this site on your twitter account.</li>
                            <li>Are following our Twitter account @flutterchain</li>
                        </ul>
                    </i>
                </div>
                <div className='Activation-box'>
                    <button onClick={(e) => {
                        window.open("https://discord.com/api/oauth2/authorize?client_id=1084465922548445236&redirect_uri=http%3A%2F%2F127.0.0.1%3A3000%2F&response_type=code&scope=identify", "parent")
                    }} className='Buttons'>Join Discord</button>
                </div>
            </header>
        </div>
    )
}


export default DiscordRedirect;